import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="bg-black">
      <body className="mx-4 my-8 justify-center items-center md:mx-12 lg:mx-48">
        {children}
      </body>
    </html>
  );
}
